### PR TITLE
Add banner to readme

### PR DESCRIPTION
**Pull request by RISC-VLIW**
Ignore the first commit lol, I added an svg file of the banner, as I went with something more simple for the logo, and I added it to the readme, I will provide a psd if you ever need it, if there's anything else that might need to be changed or doesn't quite suit your vision, let me know, thanks!

### CODE REVIEW

**Comment by RISC-VLIW** [comment]
you will likely have to change it a bit to make the path the same as your repo

**Comment by JPeisach** [comment]
hmm its a bit big, can you get rid of the transparent/empty space around it?

**Comment by RISC-VLIW** [comment]
the transparent/empty space disappears when embedded, and I'll find a way to make it a bit smaller

**Comment by RISC-VLIW** [comment]
Is that a more acceptable size?

**Comment by JPeisach** [comment]
Hmm on mobile it seems to be a bit small image

**Comment by JPeisach** [comment]
Once I check how it looks on laptop and if it's a good size I'll merge the PR

**Pull request merged**
